apiVersion: apps/v1
kind: Deployment
metadata:
    name: nimat-k8s-api
    labels:
        microserice: nimat-k8s-api
spec:
    replicas: 2
    revisionHistoryLimit: 0
    selector:
        matchLabels:
            microservice: nimat-k8s-api
    template:
        metadata:
            labels:
                microservice: nimat-k8s-api
        spec:
            containers:
            - name: nimat-k8s-api
              image: nicolasances/nimat-k8s-api:0.2.1
              ports:
              - containerPort: 8080
