apiVersion: v1
kind: Service
metadata:
    name: nimat-k8s-svc
spec:
    type: LoadBalancer
    selector:
        microservice: nimat-k8s-api
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
